version: "3.8"

services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: eventos_db_prod
    environment:
      POSTGRES_DB: eventos
      POSTGRES_USER: eventos
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventos -d eventos"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - eventos_network_prod
    restart: unless-stopped

  # Ollama para IA local
  ollama:
    image: ollama/ollama:latest
    container_name: eventos_ollama_prod
    volumes:
      - ollama_data_prod:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - eventos_network_prod
    restart: unless-stopped

  # Aplicação FastAPI
  backend:
    image: eventos:latest
    container_name: eventos_backend_prod
    environment:
      - DATABASE_URL=postgresql://eventos:${POSTGRES_PASSWORD}@db:5432/eventos
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=mistral
      - ENVIRONMENT=production
      - PORT=8000
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - eventos_network_prod
    restart: unless-stopped

  # Nginx para proxy reverso
  nginx:
    image: nginx:alpine
    container_name: eventos_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - eventos_network_prod
    restart: unless-stopped

volumes:
  postgres_data_prod:
    driver: local
  ollama_data_prod:
    driver: local

networks:
  eventos_network_prod:
    driver: bridge
