# kd-Role - Podman Compose
# Uso: podman-compose up|down

services:
  api:
    build: .
    container_name: kd_role_api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data

volumes:
  data:
